site_name: morpheus cli manual
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
pages:
  - Home: index.md
  - Setup: setup.md
  - CLI Commands: commands.md
markdown_extensions:
  - toc:
     permalink: True
