site_name: morpheus cli manual
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
pages:
  - Home: index.md
extra_css: [extra.css]
markdown_extensions:
    - toc:
        permalink: True
        baselevel: 4
