site_name: morpheus cli manual
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
nav:
  - Home: index.md
  - Setup: setup.md
  - CLI Commands: commands.md
markdown_extensions:
    - toc:
        baselevel: 1
